spring:
  application:
    name: asynchronous-http-server
  docker:
    compose:
      enabled: true
      file: ./dependencies/asynchronous-http-server/compose.yaml

project:
  ui-app:
    hosts: "*"
