spring:
  application:
    name: asynchronous-http-server
  docker:
    compose:
      enabled: true
      file: ./dependencies/asynchronous-http-server/compose.yaml
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9094}
  threads:
    virtual:
      enabled: ${ENABLE_VIRTUAL_THREADS:true}

management:
  tracing:
    enabled: ${ENABLE_TRACES:true}
    sampling:
      probability: ${TRACES_SAMPLING_RATE:1.0}
  otlp:
    tracing:
      endpoint: ${OLTP_TRACING_ENDPOINT:http://localhost:4318/v1/traces}

project:
  ui-app:
    hosts: "*"
  kafka:
    requestTopic:
      name: IncomingRequests
      partitions: 8
      replicas: 1
    responseTopic:
      name: ProcessedResponses
      partitions: 8
      replicas: 1
